### ISSUE TITLE
JSON properties must be lower camel case

### ISSUE THREAD

**Issue by cirelli94** [ercole-io/ercole#253]

**Comment by cirelli94** [comment]
- [ ] add json metadata to each struct
- [ ] godynmarshal must use json tags to marshal / unmarshal
- [ ] add tests on marshal/unmarshal model structs: get all structs with reflection, marshal bust be == unmarshal
