### ISSUE TITLE
Add settings to calculate VMware licenses

### ISSUE THREAD

**Issue by cirelli94** [ercole-io/ercole#764]
**Is your feature request related to a problem? Please describe.**

I want to be able to choose if I want to calculate only VMware licenses with ercole vms, or else of all cluster.

**Describe the solution you'd like**
Inside `api-service`:
- [ ] Create model for settings:
  - Licenses: Consider VMware clusters: (all)/(Oracle database servers)
- [ ] Add API to read and update settings: GET and PUT on `/settings`
- [ ] Add FE page for settings:
  - Licenses: Consider VMware clusters: (all)/(Oracle database servers)
- [ ] Add logic to load configuration and use it when counting VMware licenses

**Comment by rcmaiolini** [comment]
Wait information from business to create settings

**Comment by rcmaiolini** [comment]
Wait for information from the business to create settings

**Comment by rcmaiolini** [comment]
Wait for information from the business to create settings

**Comment by rcmaiolini** [comment]
Wait for information from the business to create settings

**Comment by rcmaiolini** [comment]
Wait for information from the business to create settings

**Comment by rcmaiolini** [comment]
Wait for information from the business to create settings

**Comment by rcmaiolini** [comment]
Wait for information from the business to create settings

**Comment by rcmaiolini** [comment]
Wait for information from the business to create settings

**Comment by rcmaiolini** [comment]
Wait for information from the business to create settings

**Comment by rcmaiolini** [comment]
Wait information from business to create settings

**Comment by rcmaiolini** [comment]
Wait for information from the business to create settings

**Comment by rcmaiolini** [comment]
Wait for information from the business to create settings

**Comment by rcmaiolini** [comment]
Wait for information from the business to create settings

**Comment by rcmaiolini** [comment]
Wait for information from the business to create settings

**Comment by anbrenna** [comment]
depend on #446
