### ISSUE TITLE
[TECH] Improve pagination

### ISSUE THREAD

**Issue by cirelli94** [ercole-io/ercole#811]
# Describe why ercole should be improved in this manner 

We want to reach two goals:
- Use easier standard terminology that is more clear for us
- Define a standardization to use for future api that needs pagination

# How should be improved

We want to change how pagination works.
We must start to do this changes to the api `/hosts/technologies/oracle/exadata`.

### 1. Change API params

1. Change `page` and `size` in `offset` and `limit` in controller
2. Change the service, database parts beneath it accordingly

### 2. Use Paging instead of PagingMetadata struct
Nowadays we are using PagingMetadata struct:
https://github.com/ercole-io/ercole/blob/731accfbb588349087bb716116ceb4825648e841/api-service/dto/pagination.go#L19-L27

inside: https://github.com/ercole-io/ercole/blob/731accfbb588349087bb716116ceb4825648e841/api-service/dto/oracle_exadata.go#L5

(and OracleDatabaseResponse too)

We want to make this changes:

1. Create `dto.Paging`:
    ```
   type Paging struct { 
     	Offset          int  `json:"offset"`
    	Limit          int  `json:"limit"`
    	Count          int  `json:"count"`
   }
    ```

1. Change `dto.OracleExadataResponse`: we have to [embed Paging](https://go.dev/doc/effective_go#embedding):
```
type XXXResponse struct {
	Content  []OracleExadata `json:"exadatas" bson:"content"` // Please note json:"exadatas", not json:"content"
	*Paging  `bson:"metadata"`
}
```
in order for have its fields as first-level fields of the json.
So the response will be:
```
{
    "exadatas": [...],
    "limit": 42,
    "count": 4242
}
```
If `*Paging` is nil, it will be:
```
{
    "exadatas": [...]
}
```
Without Paging values

### 3 Change every API that use pagination
We must list every API that use `page` and `size` params and change them accordingly, using `dto.XResponse` and `offset`/`limit`

# Recap
- [ ] Change `page` and `size` in `offset` and `limit` of `/hosts/technologies/oracle/databases`
- [ ] Use `Paging` instead of `PagingMetadata` struct for `dto.OracleExadataResponse`
- [ ] update `/hosts/technologies/oracle/databases`: url params and Paging in OracleDatabaseResponse
